-- AlterEnum
-- Ajouter les valeurs manquantes à l'enum QrCodeType
ALTER TYPE "QrCodeType" ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE "QrCodeType" ADD VALUE IF NOT EXISTS 'SMS';
ALTER TYPE "QrCodeType" ADD VALUE IF NOT EXISTS 'LOCATION';
ALTER TYPE "QrCodeType" ADD VALUE IF NOT EXISTS 'PHONE';
ALTER TYPE "QrCodeType" ADD VALUE IF NOT EXISTS 'BITCOIN';
ALTER TYPE "QrCodeType" ADD VALUE IF NOT EXISTS 'EVENTBRITE';

